version: "3.3"


services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - network

  mongodb:
    image: mongo:4.2.2
    container_name: database
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - network

networks:
  network:
    driver: bridge


volumes:
  db-data:
